modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
# issueTrackerURL=""

[[mods]]
modId="fossilslegacy" 
version="0.0.1a"
displayName="Fossils and Archaeology Legacy" 
# updateJSONURL=""
# displayURL=""
# logoFile=""
credits="Team July and Fossils and Archaeology Revival Team!"
authors="Willatendo"
description='''
An Aether Legacy-style mod for the Fossils and Archaeology mod. This is based on the 1.3.2 and 1.2.5 versions of the mod. The Fossils and Archaeology Revival team has nothing to do with this project and it takes nothing from their wonderful mod. When it comes out for 1.18.2, make sure to play it! This is purely for people who want an older version brought to 1.19.4 and not broken.
'''

[[dependencies.fossilslegacy]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fossilslegacy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fossilslegacy]]
    modId="simplelibrary"
    mandatory=true
    versionRange="[0.2.0,0.3.0)"
    ordering="NONE"
    side="BOTH"
    